GET http://localhost:4000/api/index


###
POST http://localhost:4000/api/signup
Content-Type: application/json

{
    "id" : "5",
    "name" : "Testing",
    "email" : "Testing@gmail.com",
    "password" : "Test"
}

//   // if()
//   //  ? Click the element of the continue button
//   // ? Set the interval for the element check of 100ms
//   // ? Try to find the element from the DOM using the message text
//   // ? If the element was matched then take the screenshot and clear the interval
//   // ? if it's not matched until 45s then clear the interval
// }
